System = 1/switched = 1

Switch-system NAME BINDING
    SUBORDINATE OBJECT CLASS switch AND SUBCLASSES;
    NAMED BY
    SUPERIOR OBJECT CLASS "Rec. X.721 | ISO/IEC 10165-2:1992:system"
    AND SUBCLASSES;
    WITH ATTRIBUTE switched;
    CREATE;
    DELETE DLETE-CONTAINED-OBJECT;
REGISTERED AS {switchNameBinding 1};
